spring:
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  application:
    name: nadri

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nadri?serverTimezone=UTC&characterEncoding=UTF-8&connectTimeout=5000&socketTimeout=5000

    username: root
    password: kolkol2233

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:uploads/images/ #file: ? ?? ??? ? ??? ? ???? ?? ???? ???? ????
    cors:
      allowed-origins: http://169.213.137.35:3000

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

server:
  port: 8080
openai:
  api-key: ${OPENAI_API_KEY:}
  base-url: "https://api.openai.com"
  model: gpt-5-nano

app:
  kakao: 
    base-url: "https://dapi.kakao.com"
    rest-api-key: "${KAKAO_REST_API_KEY}"
